version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    groups:
      flutter-packages:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
    groups:
      android-build:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
